# Generated by Django 4.2.5 on 2023-10-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbatim', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(default='Client', max_length=255),
        ),
    ]
